[blue_loadout]
# Primary Color selection
team_color_id = 0
# Secondary Color selection
custom_color_id = 0
# Car type (Octane, Merc, etc)
car_id = 23
# Type of decal
decal_id = 0
# Wheel selection
wheels_id = 0
# Boost selection
boost_id = 0
# Antenna Selection
antenna_id = 0
# Hat Selection
hat_id = 0
# Paint Type (for first color)
paint_finish_id = 0
# Paint Type (for secondary color)
custom_finish_id = 0
# Engine Audio Selection
engine_audio_id = 0
# Car trail Selection
trails_id = 0
# Goal Explosion Selection
goal_explosion_id = 0

[orange_loadout]
team_color_id = 0
custom_color_id = 0
car_id = 23
decal_id = 0
wheels_id = 0
boost_id = 35
antenna_id = 0
hat_id = 0
paint_finish_id = 0
custom_finish_id = 0
engine_audio_id = 0
trails_id = 0
goal_explosion_id = 0

[blue_loadout.paint]
car_paint_id = 0
decal_paint_id = 0
wheels_paint_id = 0
boost_paint_id = 0
antenna_paint_id = 0
hat_paint_id = 0
trails_paint_id = 0
goal_explosion_paint_id = 0

[orange_loadout.paint]
car_paint_id = 0
decal_paint_id = 0
wheels_paint_id = 0
boost_paint_id = 0
antenna_paint_id = 0
hat_paint_id = 0
trails_paint_id = 0
goal_explosion_paint_id = 0
